
import type { MCQ, Note, StudyEvent, Flashcard } from './types';

export const mcqs: MCQ[] = [
  {
    id: 'mcq-1',
    topic: 'Constitution',
    question: 'Who is known as the "Father of the Indian Constitution"?',
    options: ['Mahatma Gandhi', 'Jawaharlal Nehru', 'Dr. B. R. Ambedkar', 'Sardar Vallabhbhai Patel'],
    correctAnswerIndex: 2,
    explanation: 'Dr. B. R. Ambedkar was the chairman of the Drafting Committee of the Constituent Assembly and played a pivotal role in drafting the Indian Constitution.',
  },
  {
    id: 'mcq-2',
    topic: 'Constitution',
    question: 'The Fundamental Rights in the Indian Constitution are inspired by the Constitution of which country?',
    options: ['USA', 'UK', 'Canada', 'Ireland'],
    correctAnswerIndex: 0,
    explanation: 'The concept of Fundamental Rights was borrowed from the Bill of Rights of the United States Constitution.',
  },
  {
    id: 'mcq-3',
    topic: 'Legal Aptitude',
    question: 'What does the legal principle "actus reus" refer to?',
    options: ['The guilty mind', 'The guilty act', 'The burden of proof', 'The right to remain silent'],
    correctAnswerIndex: 1,
    explanation: '"Actus reus" is a Latin term for the "guilty act." It is the physical element of a crime, as distinguished from the "mens rea" (guilty mind).',
  },
  {
    id: 'mcq-4',
    topic: 'Legal Aptitude',
    question: 'A contract entered into by a minor is considered:',
    options: ['Valid', 'Voidable', 'Void', 'Illegal'],
    correctAnswerIndex: 2,
    explanation: 'As per the Indian Contract Act, 1872, an agreement with a minor is void ab initio, meaning it is void from the very beginning.',
  },
  {
    id: 'mcq-5',
    topic: 'General Knowledge',
    question: 'The book "Discovery of India" was written by:',
    options: ['Mahatma Gandhi', 'Jawaharlal Nehru', 'Rabindranath Tagore', 'S. Radhakrishnan'],
    correctAnswerIndex: 1,
    explanation: 'Jawaharlal Nehru wrote "The Discovery of India" during his imprisonment at Ahmednagar fort in British India from 1942–1945.',
  },
  {
    id: 'mcq-6',
    topic: 'English',
    question: 'Choose the synonym for "ephemeral".',
    options: ['Eternal', 'Transient', 'Beautiful', 'Strong'],
    correctAnswerIndex: 1,
    explanation: 'Ephemeral means lasting for a very short time. "Transient" is the closest synonym.',
  },
  {
    id: 'mcq-7',
    topic: 'Current Affairs',
    question: 'Who is the current Chief Justice of India? (As of late 2023)',
    options: ['N. V. Ramana', 'U. U. Lalit', 'D. Y. Chandrachud', 'S. A. Bobde'],
    correctAnswerIndex: 2,
    explanation: 'Dhananjaya Y. Chandrachud assumed office as the 50th Chief Justice of India in November 2022.',
  },
  {
    id: 'mcq-8',
    topic: 'Logical Reasoning',
    question: 'If all cats are mammals, and all mammals have hearts, then:',
    options: ['All cats have hearts', 'Some cats have hearts', 'No cats have hearts', 'Cannot be determined'],
    correctAnswerIndex: 0,
    explanation: 'This is a simple syllogism. If A is B, and B is C, then A must be C. Therefore, all cats have hearts.',
  },
  {
    id: 'mcq-9',
    topic: 'Constitution',
    question: 'Which article of the Constitution deals with the Right to Equality?',
    options: ['Article 14', 'Article 19', 'Article 21', 'Article 32'],
    correctAnswerIndex: 0,
    explanation: 'Article 14 of the Indian Constitution guarantees to every person the right to equality before the law or the equal protection of the laws within the territory of India.',
  },
  {
    id: 'mcq-10',
    topic: 'Legal Aptitude',
    question: 'The term "defamation" refers to:',
    options: ['Harming someone\'s reputation', 'Physical assault', 'Theft of property', 'Breach of contract'],
    correctAnswerIndex: 0,
    explanation: 'Defamation is the act of communicating false statements about a person that injure the reputation of that person.',
  },
  {
    id: 'mcq-11',
    topic: 'General Knowledge',
    question: 'Which of these is not a permanent member of the UN Security Council?',
    options: ['China', 'France', 'Germany', 'Russia'],
    correctAnswerIndex: 2,
    explanation: 'The permanent members of the UN Security Council are China, France, Russia, the United Kingdom, and the United States. Germany is not a permanent member.',
  },
  {
    id: 'mcq-12',
    topic: 'English',
    question: 'What is the antonym of "garrulous"?',
    options: ['Talkative', 'Loquacious', 'Taciturn', 'Friendly'],
    correctAnswerIndex: 2,
    explanation: '"Garrulous" means excessively talkative. "Taciturn" means reserved or uncommunicative in speech, making it the correct antonym.',
  },
  {
    id: 'mcq-13',
    topic: 'Constitution',
    question: "Which amendment to the Constitution is often called the 'Mini-Constitution'?",
    options: ['42nd Amendment', '44th Amendment', '24th Amendment', '73rd Amendment'],
    correctAnswerIndex: 0,
    explanation: 'The 42nd Amendment Act, 1976, is known as the "Mini-Constitution" because it made widespread and significant changes to the Constitution.',
  },
  {
    id: 'mcq-14',
    topic: 'Legal Aptitude',
    question: 'What is the standard of proof required in a criminal case for the prosecution?',
    options: ['Preponderance of probabilities', 'Beyond a reasonable doubt', 'Clear and convincing evidence', 'Some credible evidence'],
    correctAnswerIndex: 1,
    explanation: 'In criminal law, the prosecution has the burden of proving the defendant\'s guilt "beyond a reasonable doubt," which is the highest standard of proof.',
  },
  {
    id: 'mcq-15',
    topic: 'Current Affairs',
    question: 'India\'s first mission to study the Sun is named:',
    options: ['Surya-1', 'Chandrayaan-3', 'Gaganyaan', 'Aditya-L1'],
    correctAnswerIndex: 3,
    explanation: 'Aditya-L1 is the first Indian space-based observatory-class solar mission to study the Sun.',
  },
  {
    id: 'mcq-16',
    topic: 'Logical Reasoning',
    question: 'Find the next number in the series: 2, 6, 12, 20, 30, ?',
    options: ['40', '42', '44', '46'],
    correctAnswerIndex: 1,
    explanation: 'The pattern is n*(n+1): 1*2=2, 2*3=6, 3*4=12, 4*5=20, 5*6=30, so the next is 6*7=42.',
  },
  {
    id: 'mcq-17',
    topic: 'General Knowledge',
    question: 'Where is the headquarters of the International Court of Justice located?',
    options: ['New York, USA', 'Geneva, Switzerland', 'The Hague, Netherlands', 'Paris, France'],
    correctAnswerIndex: 2,
    explanation: 'The International Court of Justice (ICJ) has its seat at the Peace Palace in The Hague, Netherlands.',
  },
  {
    id: 'mcq-18',
    topic: 'English',
    question: 'What does the idiom "to hit the nail on the head" mean?',
    options: ['To make a mistake', 'To do or say something exactly right', 'To work very hard', 'To give up'],
    correctAnswerIndex: 1,
    explanation: 'The idiom means to describe a situation or problem with perfect accuracy.',
  },
  {
    id: 'mcq-19',
    topic: 'Constitution',
    question: 'How long did it take the Constituent Assembly to draft the Constitution of India?',
    options: ['1 year, 10 months, 12 days', '2 years, 11 months, 18 days', '3 years, 5 months, 26 days', '4 years, 2 months, 5 days'],
    correctAnswerIndex: 1,
    explanation: 'The Constituent Assembly took 2 years, 11 months, and 18 days to finalize the Indian Constitution.',
  },
  {
    id: 'mcq-20',
    topic: 'Legal Aptitude',
    question: 'The legal term "obiter dicta" refers to:',
    options: ['The legally binding part of a judgment', 'A saying by the way that is not legally binding', 'The final order of the court', 'A previously decided case'],
    correctAnswerIndex: 1,
    explanation: '"Obiter dicta" are remarks or observations made by a judge that are not essential to the decision and are not legally binding as precedent.',
  },
  {
    id: 'mcq-21',
    topic: 'Current Affairs',
    question: 'The G20 Summit in 2023 was hosted by which country?',
    options: ['Brazil', 'South Africa', 'India', 'Indonesia'],
    correctAnswerIndex: 2,
    explanation: 'India hosted the 18th G20 Heads of State and Government Summit in New Delhi in September 2023.',
  },
  {
    id: 'mcq-22',
    topic: 'Logical Reasoning',
    question: 'A man points to a photograph and says, "The lady in the photograph is my nephew\'s maternal grandmother." How is the lady in the photograph related to the man\'s sister who has no other sister?',
    options: ['Cousin', 'Sister-in-law', 'Mother', 'Mother-in-law'],
    correctAnswerIndex: 2,
    explanation: 'My nephew\'s maternal grandmother is my mother. The lady is the man\'s mother.',
  },
  {
    id: 'mcq-23',
    topic: 'English',
    question: 'Choose the correct antonym for "mitigate".',
    options: ['Alleviate', 'Lessen', 'Aggravate', 'Soothe'],
    correctAnswerIndex: 2,
    explanation: 'To mitigate is to make something less severe or painful. To "aggravate" is to make a problem worse, which is the direct opposite.',
  },
  {
    id: 'mcq-24',
    topic: 'General Knowledge',
    question: 'Who was the first woman to become a judge of the Supreme Court of India?',
    options: ['Leila Seth', 'Anna Chandy', 'M. Fathima Beevi', 'Sujata Manohar'],
    correctAnswerIndex: 2,
    explanation: 'Justice M. Fathima Beevi was the first female judge appointed to the Supreme Court of India in 1989.',
  },
  {
    id: 'mcq-25',
    topic: 'Constitution',
    question: 'The words "SOCIALIST SECULAR" were added to the Preamble by which amendment?',
    options: ['42nd Amendment', '44th Amendment', '1st Amendment', '24th Amendment'],
    correctAnswerIndex: 0,
    explanation: 'The words "SOCIALIST" and "SECULAR" were added to the Preamble of the Indian Constitution by the 42nd Amendment Act, 1976.',
  },
  {
    id: 'mcq-26',
    topic: 'Constitution',
    question: 'Under which Article can the President of India declare a financial emergency?',
    options: ['Article 352', 'Article 356', 'Article 360', 'Article 368'],
    correctAnswerIndex: 2,
    explanation: 'Article 360 of the Constitution empowers the President to proclaim a financial emergency if he is satisfied that a situation has arisen whereby the financial stability or credit of India or of any part of the territory thereof is threatened.',
  },
  {
    id: 'mcq-27',
    topic: 'Legal Aptitude',
    question: 'The principle of "Vicarious Liability" is primarily a part of:',
    options: ['Criminal Law', 'Law of Torts', 'Contract Law', 'Constitutional Law'],
    correctAnswerIndex: 1,
    explanation: 'Vicarious liability holds one person responsible for the actions of another. It is a key concept in the Law of Torts, particularly in employer-employee relationships.',
  },
  {
    id: 'mcq-28',
    topic: 'Legal Aptitude',
    question: 'What is the essential element that distinguishes theft from criminal misappropriation?',
    options: ['The value of the property', 'The intention to cause wrongful gain', 'Taking property without the owner\'s consent', 'The type of property involved'],
    correctAnswerIndex: 2,
    explanation: 'In theft, the initial taking of the property is dishonest and without the owner\'s consent. In criminal misappropriation, the offender initially possesses the property legally but then dishonestly converts it for their own use.',
  },
  {
    id: 'mcq-29',
    topic: 'General Knowledge',
    question: 'The "Dandi March" led by Mahatma Gandhi was associated with:',
    options: ['The Non-Cooperation Movement', 'The Quit India Movement', 'The Civil Disobedience Movement', 'The Khilafat Movement'],
    correctAnswerIndex: 2,
    explanation: 'The Dandi March, or Salt March, was a major act of nonviolent civil disobedience that initiated the Civil Disobedience Movement in 1930.',
  },
  {
    id: 'mcq-30',
    topic: 'English',
    question: 'Choose the correct meaning of the idiom "To bite the bullet".',
    options: ['To eat very quickly', 'To get injured', 'To face a difficult situation with courage', 'To reject an offer'],
    correctAnswerIndex: 2,
    explanation: 'The idiom "to bite the bullet" means to decide to do something difficult or unpleasant that one has been putting off or hesitating over.',
  },
  {
    id: 'mcq-31',
    topic: 'Current Affairs',
    question: 'The "James Webb Space Telescope" is a collaboration primarily between NASA and which other space agencies?',
    options: ['ISRO and Roscosmos', 'ESA and CSA', 'JAXA and CNSA', 'ISRO and ESA'],
    correctAnswerIndex: 1,
    explanation: 'The James Webb Space Telescope is an international collaboration between NASA, the European Space Agency (ESA), and the Canadian Space Agency (CSA).',
  },
  {
    id: 'mcq-32',
    topic: 'Logical Reasoning',
    question: 'In a certain code, "TEACHER" is written as "VGCEJGT". How is "CHILDREN" written in that code?',
    options: ['EJKNEGTP', 'EJKNFTGP', 'EJNFITP', 'EJKNFTGQ'],
    correctAnswerIndex: 1,
    explanation: 'The pattern is +2 for each letter. T(+2)=V, E(+2)=G, A(+2)=C, and so on. Applying this to CHILDREN: C(+2)=E, H(+2)=J, I(+2)=K, L(+2)=N, D(+2)=F, R(+2)=T, E(+2)=G, N(+2)=P. So, EJKNFTGP.',
  },
  {
    id: 'mcq-33',
    topic: 'Constitution',
    question: 'The power of the Supreme Court of India to decide disputes between the Centre and the States falls under its:',
    options: ['Advisory Jurisdiction', 'Appellate Jurisdiction', 'Original Jurisdiction', 'Writ Jurisdiction'],
    correctAnswerIndex: 2,
    explanation: 'Under Article 131, the Supreme Court has original jurisdiction in any dispute between the Government of India and one or more States, or between two or more States.',
  },
  {
    id: 'mcq-34',
    topic: 'Legal Aptitude',
    question: 'Legal Principle: "Quid pro quo" means something in return. A contract is not valid without consideration. Fact: A agrees to sell his house to B for 10 rupees. Is this a valid contract?',
    options: ['No, because 10 rupees is not adequate consideration.', 'Yes, because consideration need not be adequate, but it must be real.', 'No, it is a gift, not a contract.', 'Yes, but it is a voidable contract.'],
    correctAnswerIndex: 1,
    explanation: 'The law states that consideration must be present ("something in return"), but it does not require that the consideration be adequate. As long as some value is exchanged, the contract is valid.',
  },
  {
    id: 'mcq-35',
    topic: 'English',
    question: 'A person who is fluent in many languages is called a:',
    options: ['Linguist', 'Polyglot', 'Orator', 'Bilingual'],
    correctAnswerIndex: 1,
    explanation: 'A polyglot is someone who knows and is able to use several languages. A linguist studies language, but may not speak many.',
  },
  {
    id: 'mcq-36',
    topic: 'Logical Reasoning',
    question: 'Pointing to a girl, Rajan said, "She is the daughter of my mother\'s daughter." How is the girl related to Rajan?',
    options: ['Aunt', 'Niece', 'Cousin', 'Sister'],
    correctAnswerIndex: 1,
    explanation: 'Rajan\'s mother\'s daughter is Rajan\'s sister. The girl is the daughter of Rajan\'s sister. Therefore, the girl is Rajan\'s niece.',
  },
  {
    id: 'mcq-37',
    topic: 'General Knowledge',
    question: 'The Indus Valley Civilization is also known as the:',
    options: ['Mesopotamian Civilization', 'Harappan Civilization', 'Egyptian Civilization', 'Vedic Civilization'],
    correctAnswerIndex: 1,
    explanation: 'The Indus Valley Civilization is also called the Harappan Civilization after Harappa, the first of its sites to be excavated in the 1920s.',
  },
  {
    id: 'mcq-38',
    topic: 'Constitution',
    question: 'The idea of "Directive Principles of State Policy" in the Indian Constitution has been borrowed from the Constitution of:',
    options: ['France', 'USA', 'Ireland', 'UK'],
    correctAnswerIndex: 2,
    explanation: 'The Directive Principles of State Policy are inspired by the Irish Constitution.',
  },
  {
    id: 'mcq-39',
    topic: 'Legal Aptitude',
    question: 'An assault is:',
    options: ['The intentional application of force to another person.', 'An act which causes another person to apprehend the infliction of immediate, unlawful force.', 'A false statement that harms someone\'s reputation.', 'The unlawful confinement of a person.'],
    correctAnswerIndex: 1,
    explanation: 'Assault is an act that creates a reasonable apprehension of immediate harmful or offensive contact. The actual contact itself is called battery.',
  },
  {
    id: 'mcq-40',
    topic: 'English',
    question: 'Find the correctly spelt word.',
    options: ['Accomodate', 'Acommodate', 'Accommodate', 'Acomodate'],
    correctAnswerIndex: 2,
    explanation: 'The correct spelling is "Accommodate", with double \'c\' and double \'m\'.',
  },
  {
    id: 'mcq-41',
    topic: 'Constitution',
    question: "The concept of 'Judicial Review' in India is taken from which country's constitution?",
    options: ['United Kingdom', 'USA', 'Canada', 'Australia'],
    correctAnswerIndex: 1,
    explanation: 'The concept of Judicial Review, the power of the judiciary to examine the constitutionality of legislative enactments and executive orders, was borrowed from the Constitution of the USA.',
  },
  {
    id: 'mcq-42',
    topic: 'Constitution',
    question: 'Who administers the oath of office to the President of India?',
    options: ['The Prime Minister', 'The Speaker of the Lok Sabha', 'The Chief Justice of India', 'The outgoing President'],
    correctAnswerIndex: 2,
    explanation: 'The oath of office to the President of India is administered by the Chief Justice of India, and in their absence, the senior-most judge of the Supreme Court available.',
  },
  {
    id: 'mcq-43',
    topic: 'Constitution',
    question: 'Which schedule of the Indian Constitution deals with the allocation of seats in the Rajya Sabha?',
    options: ['Third Schedule', 'Fourth Schedule', 'Fifth Schedule', 'Sixth Schedule'],
    correctAnswerIndex: 1,
    explanation: 'The Fourth Schedule of the Constitution deals with the allocation of seats for states and union territories in the Rajya Sabha (Council of States).',
  },
  {
    id: 'mcq-44',
    topic: 'Constitution',
    question: 'What is the minimum age for becoming a member of the Lok Sabha?',
    options: ['21 years', '25 years', '30 years', '35 years'],
    correctAnswerIndex: 1,
    explanation: 'According to Article 84(b) of the Indian Constitution, the minimum age for a person to be a member of the Lok Sabha is 25 years.',
  },
  {
    id: 'mcq-45',
    topic: 'Constitution',
    question: 'The total number of members nominated by the President to the Rajya Sabha is:',
    options: ['2', '10', '12', '14'],
    correctAnswerIndex: 2,
    explanation: 'The President of India can nominate 12 members to the Rajya Sabha for their contributions to art, literature, science, and social services. The provision for nominating Anglo-Indians to Lok Sabha has been abolished.',
  },
  {
    id: 'mcq-46',
    topic: 'Constitution',
    question: 'Who is the ex-officio Chairman of the Rajya Sabha?',
    options: ['President of India', 'Vice-President of India', 'Prime Minister of India', 'Speaker of Lok Sabha'],
    correctAnswerIndex: 1,
    explanation: 'The Vice-President of India is the ex-officio Chairman of the Rajya Sabha (Council of States).',
  },
  {
    id: 'mcq-47',
    topic: 'Constitution',
    question: 'Which part of the Indian Constitution deals with the Panchayats?',
    options: ['Part VIII', 'Part IX', 'Part IX-A', 'Part X'],
    correctAnswerIndex: 1,
    explanation: 'Part IX of the Constitution, titled "The Panchayats," was added by the 73rd Constitutional Amendment Act of 1992.',
  },
  {
    id: 'mcq-48',
    topic: 'Constitution',
    question: 'A Money Bill can only be introduced in:',
    options: ['The Rajya Sabha', 'The Lok Sabha', 'Either House of Parliament', 'A joint session of Parliament'],
    correctAnswerIndex: 1,
    explanation: 'As per Article 110 of the Constitution, a Money Bill can only be introduced in the Lok Sabha, and that too on the recommendation of the President.',
  },
  {
    id: 'mcq-49',
    topic: 'Legal Aptitude',
    question: 'The maxim "Ubi jus ibi remedium" means:',
    options: ['No one is a judge in his own cause', 'Where there is a right, there is a remedy', 'The law does not concern itself with trifles', 'An act of God'],
    correctAnswerIndex: 1,
    explanation: 'This legal maxim means that for every legal right that is violated, the law provides a remedy to the injured person.',
  },
  {
    id: 'mcq-50',
    topic: 'Legal Aptitude',
    question: 'What does "pro bono publico" mean?',
    options: ['For the public good', 'In good faith', 'A guilty mind', 'Something for something'],
    correctAnswerIndex: 0,
    explanation: '"Pro bono publico" is a Latin phrase that means "for the public good." It often refers to legal work undertaken voluntarily and without payment.',
  },
  {
    id: 'mcq-51',
    topic: 'Legal Aptitude',
    question: "'Battery' in the Law of Torts is defined as:",
    options: ['Threatening to cause harm', 'The intentional and direct application of force to another person', 'Damaging someone\'s reputation', 'Unlawful entry onto another\'s land'],
    correctAnswerIndex: 1,
    explanation: 'Battery is the actual act of inflicting unlawful physical harm or offensive contact upon a person. It is intentional and non-consensual.',
  },
  {
    id: 'mcq-52',
    topic: 'Legal Aptitude',
    question: 'The principle of "Res Ipsa Loquitur" is used to infer:',
    options: ['Malice', 'Intention', 'Negligence', 'Consent'],
    correctAnswerIndex: 2,
    explanation: '"Res Ipsa Loquitur" means "the thing speaks for itself." It is a doctrine that allows a plaintiff to infer negligence from the very nature of an accident or injury in the absence of direct evidence on how any defendant behaved.',
  },
  {
    id: 'mcq-53',
    topic: 'Legal Aptitude',
    question: "A 'plaintiff' is a person who:",
    options: ['Defends against a lawsuit', 'Files a lawsuit', 'Acts as a judge in a case', 'Is a witness in a case'],
    correctAnswerIndex: 1,
    explanation: 'The plaintiff is the party who initiates a lawsuit (also known as an action) before a court.',
  },
  {
    id: 'mcq-54',
    topic: 'Legal Aptitude',
    question: "An 'injunction' is a court order that:",
    options: ['Awards monetary compensation', 'Declares a law unconstitutional', 'Compels or prevents a specific action', 'Sentences a person to prison'],
    correctAnswerIndex: 2,
    explanation: 'An injunction is a judicial remedy issued in the form of a court order that compels a party to do or refrain from doing specific acts.',
  },
  {
    id: 'mcq-55',
    topic: 'Legal Aptitude',
    question: "The term 'alibi' in criminal law is a:",
    options: ['Type of evidence', 'Confession of guilt', 'Defense of being elsewhere', 'Plea for a lighter sentence'],
    correctAnswerIndex: 2,
    explanation: 'An alibi is a defense in which a defendant claims to have been at another place at the time a crime was committed.',
  },
  {
    id: 'mcq-56',
    topic: 'Legal Aptitude',
    question: "'Slander' is a form of defamation that is communicated through:",
    options: ['Writing', 'Spoken words', 'Gestures', 'All of the above'],
    correctAnswerIndex: 1,
    explanation: 'Defamation is divided into slander (spoken defamation) and libel (written or published defamation).',
  },
  {
    id: 'mcq-57',
    topic: 'General Knowledge',
    question: "Who is the author of 'Arthashastra'?",
    options: ['Kalidasa', 'Vishakhadatta', 'Kautilya', 'Banabhatta'],
    correctAnswerIndex: 2,
    explanation: 'The Arthashastra is an ancient Indian treatise on statecraft, economic policy, and military strategy, attributed to Kautilya (also known as Chanakya).',
  },
  {
    id: 'mcq-58',
    topic: 'General Knowledge',
    question: 'The First Battle of Panipat in 1526 was fought between:',
    options: ['Akbar and Hemu', 'Babur and Ibrahim Lodi', 'Humayun and Sher Shah Suri', 'Ahmed Shah Abdali and the Marathas'],
    correctAnswerIndex: 1,
    explanation: 'The First Battle of Panipat was fought between the invading forces of Babur and the Lodi dynasty, which marked the beginning of the Mughal Empire in India.',
  },
  {
    id: 'mcq-59',
    topic: 'General Knowledge',
    question: 'What is the capital city of Australia?',
    options: ['Sydney', 'Melbourne', 'Canberra', 'Perth'],
    correctAnswerIndex: 2,
    explanation: 'While Sydney and Melbourne are larger and more famous, Canberra was chosen as the capital city of Australia in 1908 as a compromise between the two rivals.',
  },
  {
    id: 'mcq-60',
    topic: 'General Knowledge',
    question: 'The Durand Line forms the border between:',
    options: ['India and Pakistan', 'India and Afghanistan', 'Afghanistan and Pakistan', 'India and China'],
    correctAnswerIndex: 2,
    explanation: 'The Durand Line is the international 2,670-kilometer land border between Afghanistan and Pakistan in South-Central Asia.',
  },
  {
    id: 'mcq-61',
    topic: 'General Knowledge',
    question: 'Who was the first Indian to win a Nobel Prize?',
    options: ['C. V. Raman', 'Mother Teresa', 'Amartya Sen', 'Rabindranath Tagore'],
    correctAnswerIndex: 3,
    explanation: 'Rabindranath Tagore was the first Indian (and first non-European) to win the Nobel Prize in Literature in 1913 for his work "Gitanjali".',
  },
  {
    id: 'mcq-62',
    topic: 'General Knowledge',
    question: 'Which planet in our solar system is known as the "Red Planet"?',
    options: ['Venus', 'Mars', 'Jupiter', 'Saturn'],
    correctAnswerIndex: 1,
    explanation: 'Mars is often called the "Red Planet" because the iron oxide prevalent on its surface gives it a reddish appearance.',
  },
  {
    id: 'mcq-63',
    topic: 'General Knowledge',
    question: 'The scientific study of earthquakes is called:',
    options: ['Geology', 'Seismology', 'Meteorology', 'Volcanology'],
    correctAnswerIndex: 1,
    explanation: 'Seismology is the scientific study of earthquakes and the propagation of elastic waves (seismic waves) through the Earth.',
  },
  {
    id: 'mcq-64',
    topic: 'General Knowledge',
    question: 'Who founded the Mauryan Empire?',
    options: ['Ashoka', 'Bindusara', 'Chandragupta Maurya', 'Bimbisara'],
    correctAnswerIndex: 2,
    explanation: 'The Mauryan Empire was founded in 322 BCE by Chandragupta Maurya, who had overthrown the Nanda Dynasty.',
  },
  {
    id: 'mcq-65',
    topic: 'General Knowledge',
    question: 'The headquarters of UNESCO is located in:',
    options: ['Geneva, Switzerland', 'New York, USA', 'Paris, France', 'Rome, Italy'],
    correctAnswerIndex: 2,
    explanation: 'The headquarters of the United Nations Educational, Scientific and Cultural Organization (UNESCO) is located in Paris, France.',
  },
  {
    id: 'mcq-66',
    topic: 'English',
    question: "What is the one-word substitution for 'a place where birds are kept'?",
    options: ['Aquarium', 'Apiary', 'Aviary', 'Zoo'],
    correctAnswerIndex: 2,
    explanation: 'An aviary is a large cage, building, or enclosure for keeping birds in. An apiary is for bees.',
  },
  {
    id: 'mcq-67',
    topic: 'English',
    question: "What is the synonym for 'obfuscate'?",
    options: ['Clarify', 'Simplify', 'Explain', 'Confuse'],
    correctAnswerIndex: 3,
    explanation: 'To obfuscate means to make something obscure, unclear, or unintelligible. "Confuse" is the closest synonym.',
  },
  {
    id: 'mcq-68',
    topic: 'English',
    question: "What is the antonym for 'benevolent'?",
    options: ['Generous', 'Kind', 'Malevolent', 'Helpful'],
    correctAnswerIndex: 2,
    explanation: 'Benevolent means well-meaning and kindly. Malevolent means having or showing a wish to do evil to others.',
  },
  {
    id: 'mcq-69',
    topic: 'English',
    question: "What does the idiom 'a blessing in disguise' mean?",
    options: ['A solution that is obvious', 'A bad thing that seems good at first', 'A good thing that seemed bad at first', 'Something that is impossible to achieve'],
    correctAnswerIndex: 2,
    explanation: 'The idiom refers to something that appears to be a misfortune at first but turns out to have unexpected benefits.',
  },
  {
    id: 'mcq-70',
    topic: 'English',
    question: 'Choose the correctly spelled word.',
    options: ['Entreprenuer', 'Entrepranur', 'Entrepreneur', 'Entreprenur'],
    correctAnswerIndex: 2,
    explanation: 'The correct spelling for a person who sets up a business, taking on financial risks, is "Entrepreneur".',
  },
  {
    id: 'mcq-71',
    topic: 'English',
    question: "The idiom 'to be in a tight corner' means:",
    options: ['To be in a small room', 'To be in a difficult situation', 'To be very organized', 'To be secretive'],
    correctAnswerIndex: 1,
    explanation: 'Being "in a tight corner" or "in a tight spot" means being in a situation that is hard to get out of.',
  },
  {
    id: 'mcq-72',
    topic: 'English',
    question: 'A person who is indifferent to the pleasures and pains of life is known as a:',
    options: ['Hedonist', 'Ascetic', 'Stoic', 'Epicurean'],
    correctAnswerIndex: 2,
    explanation: 'A stoic is a person who can endure pain or hardship without showing their feelings or complaining.',
  },
  {
    id: 'mcq-73',
    topic: 'English',
    question: "Find the synonym of 'lucid'.",
    options: ['Vague', 'Murky', 'Clear', 'Complicated'],
    correctAnswerIndex: 2,
    explanation: 'Lucid means expressed clearly or easy to understand. "Clear" is a direct synonym.',
  },
  {
    id: 'mcq-74',
    topic: 'Logical Reasoning',
    question: 'Which word does NOT belong with the others?',
    options: ['Guitar', 'Flute', 'Violin', 'Cello'],
    correctAnswerIndex: 1,
    explanation: 'Guitar, Violin, and Cello are string instruments. A flute is a wind instrument.',
  },
  {
    id: 'mcq-75',
    topic: 'Logical Reasoning',
    question: "If 'Book' is to 'Read', then 'Fork' is to:",
    options: ['Cut', 'Eat', 'Spoon', 'Food'],
    correctAnswerIndex: 1,
    explanation: 'A book is an object used for the action of reading. A fork is an object used for the action of eating.',
  },
  {
    id: 'mcq-76',
    topic: 'Logical Reasoning',
    question: 'Complete the series: 3, 7, 15, 31, 63, ?',
    options: ['125', '126', '127', '128'],
    correctAnswerIndex: 2,
    explanation: 'The pattern is (previous number * 2) + 1. (3*2)+1=7, (7*2)+1=15, (15*2)+1=31, (31*2)+1=63, so (63*2)+1=127.',
  },
  {
    id: 'mcq-77',
    topic: 'Logical Reasoning',
    question: "A is B's sister. C is B's mother. D is C's father. How is A related to D?",
    options: ['Grandmother', 'Grandfather', 'Granddaughter', 'Daughter'],
    correctAnswerIndex: 2,
    explanation: "If C is B's mother, and A is B's sister, then C is also A's mother. If D is C's father, then D is A's maternal grandfather. Therefore, A is D's granddaughter.",
  },
  {
    id: 'mcq-78',
    topic: 'Logical Reasoning',
    question: 'Arrange the words in a meaningful sequence: 1. Police 2. Punishment 3. Crime 4. Judge 5. Judgment',
    options: ['3, 1, 4, 5, 2', '3, 1, 2, 4, 5', '1, 2, 3, 4, 5', '3, 1, 5, 4, 2'],
    correctAnswerIndex: 0,
    explanation: 'The logical sequence of events is: A Crime is committed (3), the Police investigate (1), the case goes to a Judge (4), who delivers a Judgment (5), which results in a Punishment (2).',
  },
  {
    id: 'mcq-79',
    topic: 'Logical Reasoning',
    question: "'Odometer' is to 'Mileage' as 'Compass' is to:",
    options: ['Speed', 'Direction', 'Needle', 'Hiking'],
    correctAnswerIndex: 1,
    explanation: 'An odometer is an instrument used to measure mileage (distance). A compass is an instrument used to determine direction.',
  },
  {
    id: 'mcq-80',
    topic: 'Current Affairs',
    question: 'Who won the Wimbledon Men\'s Singles title in 2023?',
    options: ['Novak Djokovic', 'Roger Federer', 'Rafael Nadal', 'Carlos Alcaraz'],
    correctAnswerIndex: 3,
    explanation: 'Carlos Alcaraz of Spain won the 2023 Wimbledon Championships Men\'s Singles title, defeating Novak Djokovic in the final.',
  },
  {
    id: 'mcq-81',
    topic: 'Current Affairs',
    question: 'The term \'Fintech\' is a portmanteau of:',
    options: ['Finance and Technology', 'Final Technique', 'Finish and Text', 'Future Technology'],
    correctAnswerIndex: 0,
    explanation: 'Fintech is a combination of the words "finance" and "technology" and refers to any technology used to improve or automate financial services.',
  },
  {
    id: 'mcq-82',
    topic: 'Current Affairs',
    question: 'Which country successfully landed the Chandrayaan-3 spacecraft on the south pole of the Moon in 2023?',
    options: ['USA', 'China', 'Russia', 'India'],
    correctAnswerIndex: 3,
    explanation: 'India made history by becoming the first country to successfully land a spacecraft, Chandrayaan-3, on the lunar south pole in August 2023.',
  },
  {
    id: 'mcq-83',
    topic: 'Current Affairs',
    question: 'The \'BRICS\' group of emerging economies originally consisted of Brazil, Russia, India, and China. Which country was added later to form "BRICS"?',
    options: ['Singapore', 'South Africa', 'Saudi Arabia', 'Spain'],
    correctAnswerIndex: 1,
    explanation: 'South Africa was formally invited to join the BRIC group in 2010, resulting in the acronym being changed to BRICS.',
  },
  {
    id: 'mcq-84',
    topic: 'Current Affairs',
    question: 'What does \'ChatGPT\' stand for?',
    options: ['Chat Global Protocol Technology', 'Chat Generative Pre-trained Transformer', 'Chat General Purpose Tool', 'Chat Graphical Processing Task'],
    correctAnswerIndex: 1,
    explanation: 'ChatGPT stands for Chat Generative Pre-trained Transformer. It is a large language model-based chatbot developed by OpenAI.',
  },
  {
    id: 'mcq-85',
    topic: 'Current Affairs',
    question: 'The Nobel Peace Prize for 2023 was awarded to Narges Mohammadi for her fight against the oppression of women in which country?',
    options: ['Afghanistan', 'Saudi Arabia', 'Iran', 'Syria'],
    correctAnswerIndex: 2,
    explanation: 'Narges Mohammadi, an imprisoned Iranian human rights activist, was awarded the Nobel Peace Prize 2023 for her work fighting for women\'s rights and democracy in Iran.',
  },
  {
    id: 'mcq-86',
    topic: 'Current Affairs',
    question: "'Operation Ganga' was an initiative by the Indian government to evacuate its citizens from:",
    options: ['Afghanistan', 'Ukraine', 'Sudan', 'Israel'],
    correctAnswerIndex: 1,
    explanation: 'Operation Ganga was an evacuation mission by the Government of India to evacuate its citizens stranded in neighboring countries during the 2022 Russian invasion of Ukraine.',
  },
  {
    id: 'mcq-87',
    topic: 'Current Affairs',
    question: 'Who was appointed as the CEO of YouTube in February 2023?',
    options: ['Susan Wojcicki', 'Sundar Pichai', 'Neal Mohan', 'Satya Nadella'],
    correctAnswerIndex: 2,
    explanation: 'Indian-American executive Neal Mohan was appointed as the new CEO of YouTube in February 2023, succeeding Susan Wojcicki.',
  },
  {
    id: 'mcq-88',
    topic: 'Current Affairs',
    question: 'The 2024 Summer Olympics are scheduled to be held in which city?',
    options: ['Los Angeles', 'Brisbane', 'Tokyo', 'Paris'],
    correctAnswerIndex: 3,
    explanation: 'The 2024 Summer Olympics, officially the Games of the XXXIII Olympiad, are scheduled to take place in Paris, France.',
  },
  {
    id: 'mcq-89',
    topic: 'Constitution',
    question: 'The Eighth Schedule of the Indian Constitution recognizes how many official languages?',
    options: ['18', '20', '22', '24'],
    correctAnswerIndex: 2,
    explanation: 'The Eighth Schedule to the Constitution of India lists the official languages of the Republic of India. It currently recognizes 22 languages.',
  },
  {
    id: 'mcq-90',
    topic: 'Legal Aptitude',
    question: 'In the context of a contract, \'coercion\' as defined by the Indian Contract Act, 1872, involves:',
    options: ['Persuasion', 'Emotional pressure', 'Committing or threatening to commit an act forbidden by the IPC', 'Providing false information'],
    correctAnswerIndex: 2,
    explanation: 'Section 15 of the Indian Contract Act defines coercion as committing, or threatening to commit, any act forbidden by the Indian Penal Code, or the unlawful detaining, or threatening to detain, any property.',
  },
  {
    id: 'mcq-91',
    topic: 'Constitution',
    question: 'Who has the power to promulgate ordinances when the Parliament is not in session?',
    options: ['The Prime Minister', 'The Chief Justice of India', 'The President of India', 'The Speaker of the Lok Sabha'],
    correctAnswerIndex: 2,
    explanation: 'Article 123 of the Constitution grants the President of India the power to promulgate ordinances during the recess of Parliament. These ordinances have the same force and effect as an Act of Parliament.',
  },
  {
    id: 'mcq-92',
    topic: 'Legal Aptitude',
    question: 'The legal maxim "audi alteram partem" means:',
    options: ['No one can be a judge in his own case', 'Let the other side be heard as well', 'The thing speaks for itself', 'An act of God'],
    correctAnswerIndex: 1,
    explanation: 'A fundamental principle of natural justice, "audi alteram partem" means that no person should be judged without a fair hearing in which each party is given the opportunity to respond to the evidence against them.',
  },
  {
    id: 'mcq-93',
    topic: 'English',
    question: 'What does the idiom "to steal someone\'s thunder" mean?',
    options: ['To physically steal something valuable', 'To take credit for someone else\'s work or idea', 'To make a loud noise', 'To scare someone'],
    correctAnswerIndex: 1,
    explanation: 'The idiom means to win praise for oneself by pre-empting someone else\'s attempt to impress.',
  },
  {
    id: 'mcq-94',
    topic: 'General Knowledge',
    question: 'The Saka Era was started by which ruler?',
    options: ['Ashoka', 'Kanishka', 'Harsha', 'Chandragupta Vikramaditya'],
    correctAnswerIndex: 1,
    explanation: 'The Saka Era, which is used as the official civil calendar in India, is believed to have been founded by the Kushan king Kanishka in 78 CE.',
  },
  {
    id: 'mcq-95',
    topic: 'Logical Reasoning',
    question: 'Find the odd one out: January, May, July, November',
    options: ['January', 'May', 'July', 'November'],
    correctAnswerIndex: 3,
    explanation: 'January, May, and July all have 31 days. November has 30 days.',
  },
  {
    id: 'mcq-96',
    topic: 'Constitution',
    question: 'The procedure for the amendment of the Indian Constitution is provided in which article?',
    options: ['Article 360', 'Article 368', 'Article 370', 'Article 356'],
    correctAnswerIndex: 1,
    explanation: 'Article 368 in Part XX of the Constitution of India provides for the procedure for amending the Constitution by the Parliament.',
  },
  {
    id: 'mcq-97',
    topic: 'Legal Aptitude',
    question: 'What is a "tort"?',
    options: ['A criminal offense', 'A breach of contract', 'A civil wrong for which a remedy is usually damages', 'A type of tax'],
    correctAnswerIndex: 2,
    explanation: 'A tort is an act or omission that gives rise to injury or harm to another and amounts to a civil wrong for which courts impose liability. The most common remedy is an award of damages.',
  },
  {
    id: 'mcq-98',
    topic: 'English',
    question: 'A person who hates humankind and avoids human society is called a:',
    options: ['Philanthropist', 'Misanthrope', 'Optimist', 'Altruist'],
    correctAnswerIndex: 1,
    explanation: 'A misanthrope is a person who dislikes humankind and avoids human society. A philanthropist is someone who seeks to promote the welfare of others.',
  },
  {
    id: 'mcq-99',
    topic: 'Logical Reasoning',
    question: 'Look at this series: 7, 10, 8, 11, 9, 12, ... What number should come next?',
    options: ['7', '10', '12', '13'],
    correctAnswerIndex: 1,
    explanation: 'This is an alternating series. The first pattern is 7, 8, 9, ... (add 1). The second pattern is 10, 11, 12, ... (add 1). The next number in the first pattern is 10.',
  },
  {
    id: 'mcq-100',
    topic: 'General Knowledge',
    question: 'Who wrote the Indian National Anthem, "Jana Gana Mana"?',
    options: ['Bankim Chandra Chatterjee', 'Rabindranath Tagore', 'Sarojini Naidu', 'Swami Vivekananda'],
    correctAnswerIndex: 1,
    explanation: 'The Indian National Anthem, "Jana Gana Mana," was composed by Rabindranath Tagore in its original Bengali version.',
  },
  {
    id: 'mcq-101',
    topic: 'Constitution',
    question: 'The concept of a "Union of States" in the Indian Constitution was adopted from which country?',
    options: ['USA (American Model)', 'Australia', 'Canada (Canadian Model)', 'United Kingdom'],
    correctAnswerIndex: 2,
    explanation: 'The phrase "Union of States" has been preferred to "Federation of States" to indicate that the Indian federation is not the result of an agreement by the states to join a federation and that states have no right to secede. This is a key feature of the Canadian model.',
  }
];

export const notes: Note[] = [
  {
    topic: 'Constitution',
    content: `The Constitution of India is the supreme law of India. It lays down the framework defining fundamental political principles, establishes the structure, procedures, powers, and duties of government institutions, and sets out fundamental rights, directive principles, and the duties of citizens. Key areas to study include: Preamble, Fundamental Rights & Duties, Directive Principles of State Policy (DPSP), Union & State Legislature, Judiciary, and Emergency provisions.`,
    links: [
      { title: 'Constitution of India (Full Text)', url: 'https://legislative.gov.in/constitution-of-india' },
      { title: 'Important Articles of Indian Constitution', url: 'https://byjus.com/ias/important-articles-in-constitution-of-india/' },
    ],
  },
  {
    topic: 'Legal Aptitude',
    content: `Legal Aptitude tests your problem-solving ability and understanding of legal principles. You'll be given legal principles and a factual situation, and you must apply the principle to the facts. Key topics: Law of Torts (defamation, negligence), Law of Contracts (essentials of a contract, breach), and basic concepts of Criminal Law (actus reus, mens rea).`,
    links: [{ title: 'Introduction to Law of Torts', url: 'https://www.law.cornell.edu/wex/tort' }],
  },
  {
    topic: 'General Knowledge',
    content: `General Knowledge covers a vast area including History, Geography, General Science, and Economics. For law entrance, focus on static GK related to civics, Indian history (especially the freedom struggle), and basic world geography.`,
    links: [{ title: 'Lucent\'s General Knowledge (Book)', url: 'https://www.amazon.in/Lucents-General-Knowledge-S-Pandey/dp/9384761544' }],
  },
  {
    topic: 'English',
    content: `The English section assesses your language proficiency. It typically includes Reading Comprehension, Grammar (Tenses, Articles, Prepositions), Vocabulary (Synonyms, Antonyms), and identifying errors in sentences. A strong reading habit is crucial.`,
    links: [{ title: 'Grammar Exercises', url: 'https://www.perfect-english-grammar.com/grammar-exercises.html' }],
  },
  {
    topic: 'Current Affairs',
    content: `This section focuses on recent events of national and international importance. Follow major newspapers and news portals daily. Pay special attention to significant legal and political developments, major government schemes, and international treaties.`,
    links: [
      { title: 'The Hindu', url: 'https://www.thehindu.com/' },
      { title: 'The Indian Express', url: 'https://indianexpress.com/' },
    ],
  },
  {
    topic: 'Logical Reasoning',
    content: `Logical Reasoning is divided into Analytical Reasoning and Critical Reasoning. Analytical reasoning includes puzzles, arrangements, and sequences. Critical reasoning involves arguments, assumptions, and conclusions. Practice is key to improving speed and accuracy.`,
    links: [{ title: 'Practice Logical Reasoning Questions', url: 'https://www.indiabix.com/logical-reasoning/questions-and-answers/' }],
  },
];

export const studyEvents: StudyEvent[] = [
    {
        date: new Date(new Date().setDate(new Date().getDate() + 1)),
        title: 'Revise Fundamental Rights',
        description: 'Go through Articles 12-35 of the Constitution.'
    },
    {
        date: new Date(new Date().setDate(new Date().getDate() + 2)),
        title: 'Practice 50 MCQs on Torts',
        description: 'Focus on negligence and defamation.'
    },
    {
        date: new Date(new Date().setDate(new Date().getDate() + 3)),
        title: 'Read a newspaper editorial',
        description: 'Summarize the main arguments.'
    }
];

export const flashcards: Flashcard[] = [
  { id: 'fc-1', term: 'Habeas Corpus', definition: 'A writ requiring a person under arrest to be brought before a judge or into court, especially to secure the person\'s release unless lawful grounds are shown for their detention.', topic: 'Legal Writs' },
  { id: 'fc-2', term: 'Mens Rea', definition: 'The intention or knowledge of wrongdoing that constitutes part of a crime, as opposed to the action or conduct of the accused (actus reus).', topic: 'Criminal Law' },
  { id: 'fc-3', term: 'Stare Decisis', definition: 'The legal principle of determining points in litigation according to precedent.', topic: 'Legal Principles' },
  { id: 'fc-4', term: 'Caveat Emptor', definition: 'The principle that the buyer alone is responsible for checking the quality and suitability of goods before a purchase is made.', topic: 'Contract Law' },
  { id: 'fc-5', term: 'Void ab initio', definition: 'A contract or legal document that is void from the very beginning.', topic: 'Contract Law' },
  { id: 'fc-6', term: 'Doli Incapax', definition: 'A legal presumption that a child under a certain age is incapable of forming criminal intent.', topic: 'Criminal Law' },
  { id: 'fc-7', term: 'Amicus Curiae', definition: 'An impartial adviser, often voluntary, to a court of law in a particular case. Translates to "friend of the court".', topic: 'Legal Roles'},
  { id: 'fc-8', term: 'Ratio Decidendi', definition: 'The rule of law on which a judicial decision is based. It is the legally binding part of a judgment.', topic: 'Legal Principles'},
];
